//
// App
//
export const SET_APP_CONFIG = 'SET_APP_CONFIG'
export const SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH'

//
// User
//
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

//
// Api
//
export const SET_API = 'SET_API'
export const SET_API_LIST = 'SET_API_LIST'
export const SET_API_FETCH_STATUS = 'SET_API_FETCH_STATUS'
export const SET_API_CURRENT_COLLECTION = 'SET_API_CURRENT_COLLECTION'

//
// Document
//
export const CLEAR_DOCUMENT_LIST = 'CLEAR_DOCUMENT_LIST'
export const SET_DOCUMENT_LIST = 'SET_DOCUMENT_LIST'
export const SET_DOCUMENT_LIST_STATUS = 'SET_DOCUMENT_LIST_STATUS'
export const CLEAR_DOCUMENT = 'CLEAR_DOCUMENT'
export const SET_DOCUMENT = 'SET_DOCUMENT'
export const SET_DOCUMENT_STATUS = 'SET_DOCUMENT_STATUS'
