module.exports = {
  AUTH_FAILED: 'AUTH_FAILED',
  INVALID_EMAIL: 'MISSING_EMAIL_ADDRESS',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  PASSWORD_RESET_INVALID: 'PASSWORD_RESET_INVALID',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
  WRONG_FORMAT: 'WRONG_FILE_FORMAT'
}
