module.exports = {
  AUTH_DISABLED: 'AUTH_DISABLED',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_UNREACHABLE: 'AUTH_UNREACHABLE',
  INVALID_EMAIL: 'MISSING_EMAIL_ADDRESS',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
}
