export const BATCH_ACTIONS = 'BATCH_ACTIONS'

//
// App
//
export const SET_APP_CONFIG = 'SET_APP_CONFIG'
export const SET_APP_STATUS = 'SET_APP_STATUS'
export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH'
export const REGISTER_NETWORK_CALL = 'REGISTER_NETWORK_CALL'

//
// User
//
export const REGISTER_FAILED_SIGN_IN = 'REGISTER_FAILED_SIGN_IN'
export const REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET'
export const REQUEST_PASSWORD_RESET_SUCCESS = 'REQUEST_PASSWORD_RESET_SUCCESS'
export const SET_REMOTE_USER = 'SET_REMOTE_USER'
export const SET_USER_STATUS = 'SET_USER_STATUS'
export const SIGN_OUT = 'SIGN_OUT'
export const UPDATE_LOCAL_USER = 'UPDATE_LOCAL_USER'

//
// Api
//
export const SET_API = 'SET_API'
export const SET_API_LIST = 'SET_API_LIST'
export const SET_API_STATUS = 'SET_API_STATUS'
export const SET_COLLECTION_PATHS = 'SET_COLLECTION_PATHS'

//
// Documents
//
export const ATTEMPT_SAVE_DOCUMENT = 'ATTEMPT_SAVE_DOCUMENT'
export const DELETE_DOCUMENTS = 'DELETE_DOCUMENTS'
export const CLEAR_DOCUMENT_LIST = 'CLEAR_DOCUMENT_LIST'
export const SET_DOCUMENT_SELECTION = 'SET_DOCUMENT_SELECTION'
export const SET_DOCUMENT_LIST_STATUS = 'SET_DOCUMENT_LIST_STATUS'
export const SET_DOCUMENT_LIST = 'SET_DOCUMENT_LIST'

//
// Document
//
export const CLEAR_REMOTE_DOCUMENT = 'CLEAR_REMOTE_DOCUMENT'
export const DISCARD_UNSAVED_CHANGES = 'DISCARD_UNSAVED_CHANGES'
export const SAVE_DOCUMENT = 'SAVE_DOCUMENT'
export const SET_DOCUMENT_PEERS = 'SET_DOCUMENT_PEERS'
export const SET_ERRORS_FROM_REMOTE_API = 'SET_ERRORS_FROM_REMOTE_API'
export const SET_FIELD_ERROR_STATUS = 'SET_FIELD_ERROR_STATUS'
export const SET_REMOTE_DOCUMENT = 'SET_REMOTE_DOCUMENT'
export const SET_REMOTE_DOCUMENT_STATUS = 'SET_REMOTE_DOCUMENT_STATUS'
export const START_NEW_DOCUMENT = 'START_NEW_DOCUMENT'
export const UPDATE_LOCAL_DOCUMENT = 'UPDATE_LOCAL_DOCUMENT'
export const USER_LEAVING_DOCUMENT = 'USER_LEAVING_DOCUMENT'

//
// Router
//
export const LOCATION_CHANGE = 'LOCATION_CHANGE'
export const ROOM_CHANGE = 'ROOM_CHANGE'
