//
// App
//
export const SET_APP_CONFIG = 'SET_APP_CONFIG'
export const SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH'
export const SET_APP_STATUS = 'SET_APP_STATUS'
export const REGISTER_NETWORK_CALL = 'REGISTER_NETWORK_CALL'

//
// User
//
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

//
// Api
//
export const SET_API = 'SET_API'
export const SET_API_STATUS = 'SET_API_STATUS'
export const SET_API_CURRENT_COLLECTION = 'SET_API_CURRENT_COLLECTION'

//
// Document
//
export const CLEAR_DOCUMENT_LIST = 'CLEAR_DOCUMENT_LIST'
export const SET_DOCUMENT_LIST = 'SET_DOCUMENT_LIST'
export const SET_DOCUMENT_LIST_STATUS = 'SET_DOCUMENT_LIST_STATUS'
export const CLEAR_REMOTE_DOCUMENT = 'CLEAR_REMOTE_DOCUMENT'
export const SET_REMOTE_DOCUMENT = 'SET_REMOTE_DOCUMENT'
export const SET_REMOTE_DOCUMENT_STATUS = 'SET_REMOTE_DOCUMENT_STATUS'
export const SET_FIELD_ERROR_STATUS = 'SET_FIELD_ERROR_STATUS'
export const UPDATE_LOCAL_DOCUMENT = 'UPDATE_LOCAL_DOCUMENT'

//
// Router
//
export const LOCATION_CHANGE = 'LOCATION_CHANGE'
