export const BATCH_ACTIONS = 'BATCH_ACTIONS'

export const STATUS_COMPLETE = 'STATUS_COMPLETE'
export const STATUS_FAILED = 'STATUS_FAILED'
export const STATUS_IDLE = 'STATUS_IDLE'
export const STATUS_LOADING = 'STATUS_LOADING'
export const STATUS_SAVING = 'STATUS_SAVING'

export const NETWORK_OK = 'NETWORK_OK'
export const NETWORK_NO_INTERNET_CONNECTION = 'NETWORK_NO_INTERNET_CONNECTION'
export const NETWORK_SERVER_UNRESPONSIVE = 'NETWORK_SERVER_UNRESPONSIVE'

export const NOTIFICATION_TYPE_SUCCESS = 'NOTIFICATION_TYPE_SUCCESS'
export const NOTIFICATION_TYPE_WARNING = 'NOTIFICATION_TYPE_WARNING'
export const NOTIFICATION_TYPE_ERROR = 'NOTIFICATION_TYPE_ERROR'
