export const STATUS_COMPLETE = 'STATUS_COMPLETE'
export const STATUS_FAILED = 'STATUS_FAILED'
export const STATUS_IDLE = 'STATUS_IDLE'
export const STATUS_LOADING = 'STATUS_LOADING'

export const NETWORK_OK = 'NETWORK_OK'
export const NETWORK_NO_INTERNET_CONNECTION = 'NETWORK_NO_INTERNET_CONNECTION'
export const NETWORK_SERVER_UNRESPONSIVE = 'NETWORK_SERVER_UNRESPONSIVE'
